---
ansible_user: pi
ansible_ssh_private_key_file: ~/.ssh/raspberry
host_name: pi-plex
usb_volume_label: usb_750g
transmission_username: transmission
transmission_password: password
transmission_white_list: "127.0.0.1,192.168.100.*"
