---

- name: Samba
  hosts: plex

  tasks:
  - name: Install Samba and components
    become: yes
    apt:
      pkg:
        - samba
        - samba-common-bin
        - cifs-utils 
      state: present
      update_cache: true
  
  - name: Set up samba configuration
    become: yes
    blockinfile:
      path: /etc/samba/smb.conf
      block: |
        [share]
            path = /mnt/{{ usb_volume_label }}
            read only = no
            public = yes
            writable = yes
